import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";
import Hero from "../components/hero";
import Feature from "../components/feature";
import MoreFeatures from "../components/moreFeatures";
import DemoProducts from "../components/demoProducts";
import FaqSection from "../components/faqSection";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Digigoods | Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Feature />
      <MoreFeatures />
      <DemoProducts />
      <FaqSection />
      <Footer />
    </div>
  );
}
